import tkinter as tk
from tkinter import *
from  tkinter import Label, StringVar, ttk
from tkinter.constants import RAISED
from tkinter.ttk import Button
from ProbabilidadEmpirica import empiricalProbability, arrayCreation
from tkinter.constants import END, INSERT, X
class Application(tk.Frame):

    def __init__(self, master=None):
        super().__init__(master)
        self.master = master
        self.window()
        self.stage()

    def window(self):
        self.master.title("Proyecto Probabilidad y estadistica")
        self.master.configure(width=1200, height=700)
        self.master.resizable(0,0)
        self.place(relwidth=1, relheight=1)
        

    def stage(self):
        self.ruta = "Proyecto/Archivos/simulacion_1k.csv"
        self.shots =  100000
        arrayCreation(self.ruta, self.shots)
        var = """Probabilidad de la obtencion de cartas en el juego clash royal"""
        """ventanaP.configure(background="black")"""
        self.label= tk.Label(self,text=var, font='Arial 20').pack()
        self.btn2 = tk.Button(self, text='Calcular 10k', command=self.generatethings)
        self.btn2.place(x=30, y=80)
        self.btn3 = tk.Button(self, text='Calcular 50k', command=self.generatethings2)
        self.btn3.place(x=110, y=80)
        self.btn4 = tk.Button(self, text='Calcular 100k', command=self.generatethings3)
        self.btn4.place(x=190, y=80)
        self.label= tk.Label(self,text=" Probabilidad Clasica", font='Arial 12').place(x=590, y=60)
        self.label= tk.Label(self,text="Valor,       Posibilidad", font='Arial 12').place(x=590, y=100)
        self.label= tk.Label(self,text="     2           1/139", font='Arial 12').place(x=590, y=120)
        self.label= tk.Label(self,text="     4           2/139", font='Arial 12').place(x=590, y=140)
        self.label= tk.Label(self,text="     6           3/139", font='Arial 12').place(x=590, y=160)
        self.label= tk.Label(self,text="     8           4/139", font='Arial 12').place(x=590, y=180)
        self.label= tk.Label(self,text="    10           3/139", font='Arial 12').place(x=590, y=200)
        self.label= tk.Label(self,text="    12           2/139", font='Arial 12').place(x=590, y=220)
        self.label= tk.Label(self,text="    14           4/139", font='Arial 12').place(x=590, y=240)
        self.label= tk.Label(self,text="    16           2/139", font='Arial 12').place(x=590, y=260)
        self.label= tk.Label(self,text="    17           2/139", font='Arial 12').place(x=590, y=280)
        self.label= tk.Label(self,text="    18           1/139", font='Arial 12').place(x=590, y=300)
        self.label= tk.Label(self,text="    19           2/139", font='Arial 12').place(x=590, y=320)
        self.label= tk.Label(self,text="    20           1/139", font='Arial 12').place(x=590, y=340)

    def generatethings(self):
        self.intento = 10000
        plataProbability, oroProbability, giganteProbability,magicoProbability,superMagicoProbability,superEspecialProbability,legendarioProbability,s1Probability,s2Probability,s3Probability,s4Probability,s5Probability,s6Probability,s7Probability,s8Probability,s9Probability,s10Probability,s11Probability,s12Probability=empiricalProbability(self.intento)
        self.label= tk.Label(self,text="Probabilidad de los cofres:", font='Arial 12').place(x=30,y=140)
        self.label= tk.Label(self,text="Cofre de plata:", font='Arial 12').place(x=30,y=170)
        self.label= tk.Label(self,text=round(plataProbability,4), font='Arial 12').place(x=140,y=170)
        self.label= tk.Label(self,text="Cofre de oro:", font='Arial 12').place(x=30,y=190)
        self.label= tk.Label(self,text=round(oroProbability,4), font='Arial 12').place(x=140,y=190)
        self.label= tk.Label(self,text="Cofre de gigante:", font='Arial 12').place(x=30,y=210)
        self.label= tk.Label(self,text=round(giganteProbability,4), font='Arial 12').place(x=160,y=210)
        self.label= tk.Label(self,text="Cofre de magico:", font='Arial 12').place(x=30,y=235)
        self.label= tk.Label(self,text=round(magicoProbability,4), font='Arial 12').place(x=160,y=235)
        self.label= tk.Label(self,text="Cofre de Super Magico:", font='Arial 12').place(x=30,y=260)
        self.label= tk.Label(self,text=round(superMagicoProbability,4), font='Arial 12').place(x=200,y=260)
        self.label= tk.Label(self,text="Cofre de Super Especial:", font='Arial 12').place(x=30,y=280)
        self.label= tk.Label(self,text=round(superEspecialProbability,4), font='Arial 12').place(x=210,y=280)
        self.label= tk.Label(self,text="Cofre de Legendario:", font='Arial 12').place(x=30,y=300)
        self.label= tk.Label(self,text=round(legendarioProbability,4), font='Arial 12').place(x=210,y=300)
        self.label= tk.Label(self,text="Salida numero 2: ", font='Arial 12').place(x=30,y=340)
        self.label= tk.Label(self,text=round(s1Probability,4), font='Arial 12').place(x=220, y=340)
        self.label= tk.Label(self,text="Salida numero 4: ", font='Arial 12').place(x=30, y=360)
        self.label= tk.Label(self,text=round(s2Probability,4), font='Arial 12').place(x=220,y=360)
        self.label= tk.Label(self,text="Salida numero 6:", font='Arial 12').place(x=30, y=380)
        self.label= tk.Label(self,text=round(s3Probability,4), font='Arial 12').place(x=220,y=380)
        self.label= tk.Label(self,text="Salida numero 8:", font='Arial 12').place(x=30,y=400)
        self.label= tk.Label(self,text=round(s4Probability,4), font='Arial 12').place(x=220,y=400)
        self.label= tk.Label(self,text="Salida numero 10:", font='Arial 12').place(x=30,y=420)
        self.label= tk.Label(self,text=round(s5Probability,4), font='Arial 12').place(x=220,y=420)
        self.label= tk.Label(self,text="Salida numero 12:", font='Arial 12').place(x=30,y=440)
        self.label= tk.Label(self,text=round(s6Probability,4), font='Arial 12').place(x=220,y=440)
        self.label= tk.Label(self,text="Salida numero 14:", font='Arial 12').place(x=30,y=460)
        self.label= tk.Label(self,text=round(s7Probability,4), font='Arial 12').place(x=220,y=460)
        self.label= tk.Label(self,text="Salida numero 16:", font='Arial 12').place(x=30,y=480)
        self.label= tk.Label(self,text=round(s8Probability,4), font='Arial 12').place(x=220,y=480)
        self.label= tk.Label(self,text="Salida numero 17:", font='Arial 12').place(x=30,y=500)
        self.label= tk.Label(self,text=round(s9Probability,4), font='Arial 12').place(x=220,y=500)
        self.label= tk.Label(self,text="Salida numero 18:", font='Arial 12').place(x=30,y=520)
        self.label= tk.Label(self,text=round(s10Probability,4), font='Arial 12').place(x=220,y=520)
        self.label= tk.Label(self,text="Salida numero 19:", font='Arial 12').place(x=30,y=540)
        self.label= tk.Label(self,text=round(s11Probability,4,), font='Arial 12').place(x=220,y=540)
        self.label= tk.Label(self,text="Salida numero 20:", font='Arial 12').place(x=30,y=560)
        self.label= tk.Label(self,text=round(s12Probability,4), font='Arial 12').place(x=220, y= 560)
        






    def generatethings2(self):
        self.intento = 50000
        plataProbability, oroProbability, giganteProbability,magicoProbability,superMagicoProbability,superEspecialProbability,legendarioProbability,s1Probability,s2Probability,s3Probability,s4Probability,s5Probability,s6Probability,s7Probability,s8Probability,s9Probability,s10Probability,s11Probability,s12Probability=empiricalProbability(self.intento)
        self.label= tk.Label(self,text="Probabilidad de los cofres:", font='Arial 12').place(x=30,y=140)
        self.label= tk.Label(self,text="Cofre de plata:", font='Arial 12').place(x=30,y=170)
        self.label= tk.Label(self,text=round(plataProbability,4), font='Arial 12').place(x=140,y=170)
        self.label= tk.Label(self,text="Cofre de oro:", font='Arial 12').place(x=30,y=190)
        self.label= tk.Label(self,text=round(oroProbability,4), font='Arial 12').place(x=140,y=190)
        self.label= tk.Label(self,text="Cofre de gigante:", font='Arial 12').place(x=30,y=210)
        self.label= tk.Label(self,text=round(giganteProbability,4), font='Arial 12').place(x=160,y=210)
        self.label= tk.Label(self,text="Cofre de magico:", font='Arial 12').place(x=30,y=235)
        self.label= tk.Label(self,text=round(magicoProbability,4), font='Arial 12').place(x=160,y=235)
        self.label= tk.Label(self,text="Cofre de Super Magico:", font='Arial 12').place(x=30,y=260)
        self.label= tk.Label(self,text=round(superMagicoProbability,4), font='Arial 12').place(x=200,y=260)
        self.label= tk.Label(self,text="Cofre de Super Especial:", font='Arial 12').place(x=30,y=280)
        self.label= tk.Label(self,text=round(superEspecialProbability,4), font='Arial 12').place(x=210,y=280)
        self.label= tk.Label(self,text="Cofre de Legendario:", font='Arial 12').place(x=30,y=300)
        self.label= tk.Label(self,text=round(legendarioProbability,4), font='Arial 12').place(x=210,y=300)
        self.label= tk.Label(self,text="Salida numero 2: ", font='Arial 12').place(x=30,y=340)
        self.label= tk.Label(self,text=round(s1Probability,4), font='Arial 12').place(x=220, y=340)
        self.label= tk.Label(self,text="Salida numero 4: ", font='Arial 12').place(x=30, y=360)
        self.label= tk.Label(self,text=round(s2Probability,4), font='Arial 12').place(x=220,y=360)
        self.label= tk.Label(self,text="Salida numero 6:", font='Arial 12').place(x=30, y=380)
        self.label= tk.Label(self,text=round(s3Probability,4), font='Arial 12').place(x=220,y=380)
        self.label= tk.Label(self,text="Salida numero 8:", font='Arial 12').place(x=30,y=400)
        self.label= tk.Label(self,text=round(s4Probability,4), font='Arial 12').place(x=220,y=400)
        self.label= tk.Label(self,text="Salida numero 10:", font='Arial 12').place(x=30,y=420)
        self.label= tk.Label(self,text=round(s5Probability,4), font='Arial 12').place(x=220,y=420)
        self.label= tk.Label(self,text="Salida numero 12:", font='Arial 12').place(x=30,y=440)
        self.label= tk.Label(self,text=round(s6Probability,4), font='Arial 12').place(x=220,y=440)
        self.label= tk.Label(self,text="Salida numero 14:", font='Arial 12').place(x=30,y=460)
        self.label= tk.Label(self,text=round(s7Probability,4), font='Arial 12').place(x=220,y=460)
        self.label= tk.Label(self,text="Salida numero 16:", font='Arial 12').place(x=30,y=480)
        self.label= tk.Label(self,text=round(s8Probability,4), font='Arial 12').place(x=220,y=480)
        self.label= tk.Label(self,text="Salida numero 17:", font='Arial 12').place(x=30,y=500)
        self.label= tk.Label(self,text=round(s9Probability,4), font='Arial 12').place(x=220,y=500)
        self.label= tk.Label(self,text="Salida numero 18:", font='Arial 12').place(x=30,y=520)
        self.label= tk.Label(self,text=round(s10Probability,4), font='Arial 12').place(x=220,y=520)
        self.label= tk.Label(self,text="Salida numero 19:", font='Arial 12').place(x=30,y=540)
        self.label= tk.Label(self,text=round(s11Probability,4,), font='Arial 12').place(x=220,y=540)
        self.label= tk.Label(self,text="Salida numero 20:", font='Arial 12').place(x=30,y=560)
        self.label= tk.Label(self,text=round(s12Probability,4), font='Arial 12').place(x=220, y= 560)

    def generatethings3(self):
        self.intento = 100000
        plataProbability, oroProbability, giganteProbability,magicoProbability,superMagicoProbability,superEspecialProbability,legendarioProbability,s1Probability,s2Probability,s3Probability,s4Probability,s5Probability,s6Probability,s7Probability,s8Probability,s9Probability,s10Probability,s11Probability,s12Probability=empiricalProbability(self.intento)
        self.label= tk.Label(self,text="Probabilidad de los cofres:", font='Arial 12').place(x=30,y=140)
        self.label= tk.Label(self,text="Cofre de plata:", font='Arial 12').place(x=30,y=170)
        self.label= tk.Label(self,text=round(plataProbability,4), font='Arial 12').place(x=140,y=170)
        self.label= tk.Label(self,text="Cofre de oro:", font='Arial 12').place(x=30,y=190)
        self.label= tk.Label(self,text=round(oroProbability,4), font='Arial 12').place(x=140,y=190)
        self.label= tk.Label(self,text="Cofre de gigante:", font='Arial 12').place(x=30,y=210)
        self.label= tk.Label(self,text=round(giganteProbability,4), font='Arial 12').place(x=160,y=210)
        self.label= tk.Label(self,text="Cofre de magico:", font='Arial 12').place(x=30,y=235)
        self.label= tk.Label(self,text=round(magicoProbability,4), font='Arial 12').place(x=160,y=235)
        self.label= tk.Label(self,text="Cofre de Super Magico:", font='Arial 12').place(x=30,y=260)
        self.label= tk.Label(self,text=round(superMagicoProbability,4), font='Arial 12').place(x=200,y=260)
        self.label= tk.Label(self,text="Cofre de Super Especial:", font='Arial 12').place(x=30,y=280)
        self.label= tk.Label(self,text=round(superEspecialProbability,4), font='Arial 12').place(x=210,y=280)
        self.label= tk.Label(self,text="Cofre de Legendario:", font='Arial 12').place(x=30,y=300)
        self.label= tk.Label(self,text=round(legendarioProbability,4), font='Arial 12').place(x=210,y=300)
        self.label= tk.Label(self,text="Salida numero 2: ", font='Arial 12').place(x=30,y=340)
        self.label= tk.Label(self,text=round(s1Probability,4), font='Arial 12').place(x=220, y=340)
        self.label= tk.Label(self,text="Salida numero 4: ", font='Arial 12').place(x=30, y=360)
        self.label= tk.Label(self,text=round(s2Probability,4), font='Arial 12').place(x=220,y=360)
        self.label= tk.Label(self,text="Salida numero 6:", font='Arial 12').place(x=30, y=380)
        self.label= tk.Label(self,text=round(s3Probability,4), font='Arial 12').place(x=220,y=380)
        self.label= tk.Label(self,text="Salida numero 8:", font='Arial 12').place(x=30,y=400)
        self.label= tk.Label(self,text=round(s4Probability,4), font='Arial 12').place(x=220,y=400)
        self.label= tk.Label(self,text="Salida numero 10:", font='Arial 12').place(x=30,y=420)
        self.label= tk.Label(self,text=round(s5Probability,4), font='Arial 12').place(x=220,y=420)
        self.label= tk.Label(self,text="Salida numero 12:", font='Arial 12').place(x=30,y=440)
        self.label= tk.Label(self,text=round(s6Probability,4), font='Arial 12').place(x=220,y=440)
        self.label= tk.Label(self,text="Salida numero 14:", font='Arial 12').place(x=30,y=460)
        self.label= tk.Label(self,text=round(s7Probability,4), font='Arial 12').place(x=220,y=460)
        self.label= tk.Label(self,text="Salida numero 16:", font='Arial 12').place(x=30,y=480)
        self.label= tk.Label(self,text=round(s8Probability,4), font='Arial 12').place(x=220,y=480)
        self.label= tk.Label(self,text="Salida numero 17:", font='Arial 12').place(x=30,y=500)
        self.label= tk.Label(self,text=round(s9Probability,4), font='Arial 12').place(x=220,y=500)
        self.label= tk.Label(self,text="Salida numero 18:", font='Arial 12').place(x=30,y=520)
        self.label= tk.Label(self,text=round(s10Probability,4), font='Arial 12').place(x=220,y=520)
        self.label= tk.Label(self,text="Salida numero 19:", font='Arial 12').place(x=30,y=540)
        self.label= tk.Label(self,text=round(s11Probability,4,), font='Arial 12').place(x=220,y=540)
        self.label= tk.Label(self,text="Salida numero 20:", font='Arial 12').place(x=30,y=560)
        self.label= tk.Label(self,text=round(s12Probability,4), font='Arial 12').place(x=220, y= 560)
if __name__ == '__main__':
    root = tk.Tk()
    app = Application(master=root)
    app.mainloop()
